### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by rayliverified**
*Update dependencies to work with Flutter v0.8.3 and Dart v2.1.

### CODE REVIEW

**Comment by rayliverified** [comment]
Did you have a chance to test this PR?

**Comment by mdanics** [comment]
Sorry for the delay, been busy. Taking a look now, seems like there is a conflict with google play service versions, getting `Unable to merge dex`

**Comment by mdanics** [comment]
Looks like adding`multiDexEnabled true` to defaultConfig in /android/app/build.gradle fixes the issue for me. 

Before merging, want to find out if this is **what you had to do to get it to work for you**. Ideally I don't want to enable something I don't completely know what it does. 

Other than that, everything seems to be working fine - thank you for going through and updating the breaking changes for updated packages.

**Comment by rayliverified** [comment]
Thanks for looking over the PR and this app! Let me check to see if I had to enable multidex, will get back to you on this. Also, there's been so many changes since this PR I need to make sure everything is still up to date.

**Comment by rayliverified** [comment]
Just tested and you're right. I need to enable multidex in order to build. Done!

**Comment by mdanics** [comment]
Looks good! Thanks for the PR

**Comment by rayliverified** [comment]
Thank you for the quick merge! I'm learning how to build Flutter apps and your example is really helpful. There's some parts that don't work that well and if I figure out how to do it better, I'll make sure to send a PR. 

I'm currently tackling Firebase login and authentication. Fluttergram often displays the SignIn screen even when you're already logged which isn't desirable. I'm looking at how to avoid that!.

**Comment by mdanics** [comment]
Hm yeah thats not ideal. I haven't experienced that which makes it hard for me to look into it, but I agree the login logic isn't the best. 

Do you have a way we can talk privately? Would love to talk Flutter and your experience with it.

**Comment by rayliverified** [comment]
Are you part of the FlutterDev Reddit Discord? I'd love to talk Flutter too! https://discord.gg/W6eyk7

**Comment by rayliverified** [comment]
Also, my email is ray.li.verified@gmail.com

**Pull request merged**
